CREATE TABLE IF NOT EXISTS genre
(
    id   BIGINT PRIMARY KEY,
    name VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS age_rating
(
    id   BIGINT PRIMARY KEY,
    name VARCHAR(10) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL UNIQUE,
    login    VARCHAR(255) NOT NULL UNIQUE,
    name     VARCHAR(255) NOT NULL,
    birthday DATE         NOT NULL
);

CREATE TABLE IF NOT EXISTS film
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255) NOT NULL,
    description   VARCHAR(200),
    release_date  DATE         NOT NULL,
    duration      INTEGER      NOT NULL,
    age_rating_id BIGINT       NOT NULL,
    CONSTRAINT fk_film_age_rating
        FOREIGN KEY (age_rating_id) REFERENCES age_rating (id)
);

CREATE TABLE IF NOT EXISTS film_genre
(
    film_id  BIGINT NOT NULL,
    genre_id BIGINT NOT NULL,
    CONSTRAINT pk_film_genre PRIMARY KEY (film_id, genre_id),
    CONSTRAINT fk_film_genre_film
        FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT fk_film_genre_genre
        FOREIGN KEY (genre_id) REFERENCES genre (id)
);

CREATE TABLE IF NOT EXISTS user_like_film
(
    film_id    BIGINT    NOT NULL,
    user_id    BIGINT    NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_film_rating UNIQUE (film_id, user_id),
    CONSTRAINT fk_film_rating_film
        FOREIGN KEY (film_id) REFERENCES film (id) ON DELETE CASCADE,
    CONSTRAINT fk_film_rating_user
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);



CREATE TABLE IF NOT EXISTS friendship
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL,
    friend_id  BIGINT      NOT NULL,
    created_at TIMESTAMP   NOT NULL,
    CONSTRAINT uk_friendship_request UNIQUE (user_id, friend_id),
    CONSTRAINT fk_friendship_request_initiator
        FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_friendship_request_receiver
        FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT ck_friendship_request_not_self
        CHECK (user_id <> friend_id)
);